// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using lnksnp.Context;

#nullable disable

namespace lnksnp.Migrations
{
    [DbContext(typeof(LinkSnipContext))]
    partial class LinkSnipContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.10");

            modelBuilder.Entity("lnksnp.Models.LinkClick", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("IP")
                        .HasColumnType("TEXT");

                    b.Property<string>("acceptLanguage")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("clickDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("linkId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("referer")
                        .HasColumnType("TEXT");

                    b.Property<string>("userAgent")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("LinkClicks");
                });

            modelBuilder.Entity("lnksnp.Models.LinkSnip", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<string>("LongLink")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ShortLink")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("LinkSnips");
                });
#pragma warning restore 612, 618
        }
    }
}
